apiVersion: v1
entries:
  nui:
  - apiVersion: v2
    appVersion: latest
    created: "2025-11-19T08:04:30.387879371Z"
    description: NATS Free and open source UI
    digest: eecac479de251140c96c548bc82ec024704d0da2cf19277c04cc5630770da85f
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.6/nui-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: latest
    created: "2025-10-23T16:44:48.470768844Z"
    description: NATS Free and open source UI
    digest: d384acf8220ae5348272708062bf4b8f98d73d5218642d148f6d66fb5d51c898
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.5/nui-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: latest
    created: "2025-02-08T12:07:15.705283336Z"
    description: NATS Free and open source UI
    digest: ea2bad28fca0fdf0a0839dffbc007d1ba78af9ed6fabbf3965ad6c7f05db82ea
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.4/nui-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: latest
    created: "2025-01-31T19:19:38.356882414Z"
    description: NATS Free and open source UI
    digest: a2dfb11b06267119405f2ed6c7f7eac8c957d9142b3dea0f4b923b6556cbade7
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.3/nui-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: latest
    created: "2025-01-26T22:26:39.587574186Z"
    description: NATS Free and open source UI
    digest: 26d4d6dc44b62365efbd4d28ec6812c59aedc3bcde971b1c8f04ec24bafe49f1
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.2/nui-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: latest
    created: "2025-01-14T20:47:48.989813443Z"
    description: NATS Free and open source UI
    digest: ad9dcb6a77f68da7f9f6e1567eaf2c113bdd38b48823b44b41f1339181a0c4d9
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.1/nui-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2024-08-08T06:45:07.733316435Z"
    description: NATS Free and open source UI
    digest: f15eff74111a04489ebb20c90bc53e03bcbf76ee629ff85e34f3a176b2f54874
    name: nui
    type: application
    urls:
    - https://github.com/nats-nui/k8s/releases/download/nui-0.1.0/nui-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-19T08:04:30.3879052Z"
